version: "3.2"

services:
  php:
    build: .
    container_name: Liker_php
    volumes:
      - .:/var/www/Liker/
      - ./logs/php:/var/log/php
    ports:
      - 9000:9000

  nginx:
      image: nginx:latest
      container_name: Liker_nginx
      volumes:
          - .:/var/www/Liker/
          - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./logs:/var/log/nginx
      links:
          - php:php
      ports:
          - 80:80
          - 443:443

  mysql:
    container_name: Liker_mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./docker/mysql/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
